---
- hosts: mediacenters
  become: true

  vars_files:
    - vars/external_drives.yml
    - vars/plex.yml
    - vars/transmission.yml
    - vars/pymedusa.yml
    - vars/samba.yml

  pre_tasks:
    - name: "Mount external drives"
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: "{{ item.state }}"
        dump: "{{ item.dump }}"
        passno: "{{ item.passno }}"
      loop: "{{ external_drive_mounts }}"

  roles:
    - jelle_s.plex
    - danielkoster.transmission-daemon
    - jelle_s.pymedusa
    - bertvv.samba

  post_tasks:
    - name: Create the Transmission config directory
      file:
        path: /etc/systemd/system/transmission-daemon.service.d
        state: directory
        owner: root
        group: root

    - name: Configure Transmission.
      template:
        src: transmission-daemon-service-override.conf.j2
        dest: /etc/systemd/system/transmission-daemon.service.d/override.conf
        owner: root
        group: root
        mode: 0644

    - name: ensure transmission-daemon permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ transmission_service_user }}"
        group: "{{ transmission_service_group }}"
        recurse: yes
      with_items:
        - "{{ transmission_download_dir }}"
        - "{{ transmission_incomplete_dir }}"
        - "/etc/transmission-daemon"

    - name: restart transmission-daemon
      systemd:
        daemon-reload: yes
        name: transmission-daemon
        state: restarted

    - name: Ensure Transmission autostarts.
      service:
        name: transmission-daemon
        enabled: true
      notify: restart transmission-daemon
