---
- hosts: mediacenters
  become: true

  vars_files:
    - vars/external_drives.yml
    - vars/plex.yml
    - vars/transmission.yml
    - vars/pymedusa.yml
    - vars/samba.yml

  pre_tasks:
    - name: "Mount external drives"
      ansible.posix.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: "{{ item.state }}"
        dump: "{{ item.dump }}"
        passno: "{{ item.passno }}"
      loop: "{{ external_drive_mounts }}"

  roles:
    - jelle_s.plex
    - jelle_s.transmission_daemon
    - jelle_s.pymedusa
    - bertvv.samba
