---
- name: ensure transmission-daemon permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ transmission_service_user }}"
    group: "{{ transmission_service_group }}"
    recurse: yes
  with_items:
    - "{{ transmission_download_dir }}"
    - "{{ transmission_incomplete_dir }}"
    - "/etc/transmission-daemon"

- name: restart transmission-daemon
  systemd:
    daemon-reload: yes
    name: transmission-daemon
    state: restarted
